hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Iterator.o -c ./src/Iterator.cpp
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./lib/SwapNodes.o -c ./src/SwapNodes.cpp
	g++ -I ./include/ -o ./lib/Compare.o -c ./src/Compare.cpp
	g++ -I ./include/ -o ./lib/DoublyLinkedList.o -c ./src/DoublyLinkedList.cpp
	g++ -I ./include/ -o ./bin/main ./lib/DoublyLinkedList.o ./lib/Iterator.o ./lib/Node.o ./lib/Compare.o ./lib/SwapNodes.o ./src/Main.cpp



	
calistir:
	./bin/main